### PR TITLE
Fixes

### PR DESCRIPTION
**Pull request by dshanske**
This adds the testing I introduced to the other plugins. It also adds some text regarding the Press This situation.

### CODE REVIEW

**Comment by dshanske** [comment]
I am not sure why Travis is failing. Any opinions?

**Comment by miklb** [comment]
something with the unit tests and the database from looking at the logs https://travis-ci.org/indieweb/wordpress-indieweb-press-this/jobs/317437543

**Comment by dshanske** [comment]
I see, but it is the same configuration I set up for the other plugins. I feel that I am missing something obvious

**Comment by pfefferle** [comment]
See https://github.com/indieweb/wordpress-indieweb-press-this/pull/20

**Pull request merged**
